Celebrity/config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get '/signup', to:'users#new'
  post '/signup', to:'users#create'

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  
  # 画像データの取得
  get '/show_image', to: 'application#show_image'
  
  delete '/logout', to:'sessions#destroy'
  get 'skillsheets/index'
  get 'skillsheets/download'
  get 'skillsheets/update_skillsheet'
  get 'skillsheets/search'#追記
  resources :users do
      member do
        get 'get_image'
        get 'get_skillsheet'
    end
  end
  
  resources :pdca_posts
  resources :defect_forms
  resources :qiita_posts
  resources :interview_posts
  resources :account_activations, only: [:edit]
  resources :feedbacks, only: [:create, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :blogs
  resources :faq
  
  resources :movies do
    get 'sort', on: :collection
  end
  resources :movie_categories do
    get 'sort', on: :collection
  end
  resources :skillsheets
  get '/get_skillsheet', to: 'skillsheets#get_skillsheet'
  get '/index', to: 'skillsheets#index'
  patch '/update_business_status', to: 'skillsheets#update_business_status'
  resources :terms do
    collection do
      get 'ajax_search'
    end
  end
  resources :users do
      member do
        get 'get_image'
        get 'get_skillsheet'
    end
  end
  
  post '/category_create', to: 'faq#category_create'
  patch '/category_update/:id', to: 'faq#category_update'
  delete '/category_destroy/:id', to: 'faq#category_destroy'
  
  post '/tag_new', to: 'users#tag_new'
  delete '/tag_delete', to: 'users#tag_delete'
  
  # patch '/post_course', to:'users#update_course'
  patch '/post_pic', to:'users#update_picture'
  patch '/tag_edit', to:'users#tag_edit' #追加
  patch '/tag_show', to:'users#tag_show' #追加 sugi
  delete '/delete_tag', to: 'users#tag_delete' #temp post⇨deleteに変更しshow.htmlと統一
  patch '/post_skillsheet', to: 'skillsheets#update_skillsheet'
  patch '/register_status', to: 'users#register_status'
  root 'top#index'
  
  get '/information', to: 'information#show'
  post '/information', to: 'information#create', as: 'create_information'
  patch '/information', to: 'information#update'
  delete '/information', to: 'information#destroy'

  get '/basic_programming', to: 'static_pages#progate' # progate代替えとして代用修正
  post '/basic_programming', to: 'static_pages#progate' # progate代替えとして代用修正
  
  get '/attendance_system', to: 'static_pages#railstutorial' # Railsチュートリアルの代替えとして追加
  
  get '/portfolio', to: 'portfolio_comments#portfolio'
  post '/comments/create', to: 'portfolio_comments#create'
  post '/comments/:id/destroy', to: 'portfolio_comments#destroy'
  get '/qa', to: 'static_pages#qa'
  get '/portfolio_mv', to: 'static_pages#portfolio_mv'
  post '/defect_forms/notify_to_slack', to: 'defect_forms#notify_to_slack'
  patch '/html_css_status', to: 'html_css_statuses#update'
  patch '/html_css_status_schedule', to: 'html_css_statuses#update_schedule', as: 'html_css_schedule'
  patch '/html_css_status_completion', to: 'html_css_statuses#update_completion', as: 'html_css_completion'
  patch '/javascript_status', to: 'javascript_statuses#update'
  patch '/javascript_status_schedule', to: 'javascript_statuses#update_schedule', as: 'javascript_schedule'
  patch '/javascript_status_completion', to: 'javascript_statuses#update_completion', as: 'javascript_completion'
  patch '/ruby_status', to: 'ruby_statuses#update'
  patch '/ruby_status_schedule', to: 'ruby_statuses#update_schedule', as: 'ruby_schedule'
  patch '/ruby_status_completion', to: 'ruby_statuses#update_completion', as: 'ruby_completion'
  patch '/bootstrap_status', to: 'bootstrap_statuses#update'
  patch '/bootstrap_status_schedule', to: 'bootstrap_statuses#update_schedule', as: 'bootstrap_schedule'
  patch '/bootstrap_status_completion', to: 'bootstrap_statuses#update_completion', as: 'bootstrap_completion'
  patch '/rubyonrails_status', to: 'rubyonrails_statuses#update'
  patch '/rubyonrails_status_schedule', to: 'rubyonrails_statuses#update_schedule', as: 'rubyonrails_schedule'
  patch '/rubyonrails_status_completion', to: 'rubyonrails_statuses#update_completion', as: 'rubyonrails_completion'
  patch '/railstutorial_status', to: 'railstutorial_statuses#update'
  patch '/railstutorial_status_schedule', to: 'railstutorial_statuses#update_schedule', as: 'railstutorial_schedule'
  patch '/user_movie_status', to: 'user_movie_statuses#update'
  patch '/user_movie_status_schedule', to: 'user_movie_statuses#update_schedule', as: 'user_movie_schedule'
end

Celebrity/app/views/layouts/_aside.html.erb
<aside class="main-sidebar">
  <section class="sidebar">
    <!--検索フォーム-->
    <!--<form method="get" class="sidebar-form" id="sidebar-form">-->
    <!--  <div class="input-group">-->
    <!--      <input type="text" name="q" class="form-control" placeholder="Search..." id="search-input">-->
    <!--      <span class="input-group-btn">-->
    <!--          <button type="submit" name="search" id="search-btn" class="btn btn-flat">-->
    <!--              <i class="fa fa-search"></i>-->
    <!--          </button>-->
    <!--      </span>-->
    <!--  </div>-->
    <!--</form>-->
    
    <!-- Sidebar Menu -->
    <ul class="sidebar-menu tree" data-widget="tree">
      <!--adminのみ表示-->
      <% if current_user.try(:admin) %>
        <li class="header"><i class="fa fa-cog" aria-hidden="true"></i> for Administrator</li>
        <li><%= link_to '動画', movies_path %></li>
        <li><%= link_to 'お知らせ', information_path %></li>
        <li><%= link_to 'ブログ', new_blog_path %></li>
        <li><%= link_to '新規登録', signup_path %></li>
      <% end %>
      
      <% unless current_user.guest %>
        <li class="header"><i class="fa fa-bars" aria-hidden="true"></i> Contents</li>
        <!--movies menu-->
        <li class="treeview">
          <a href="#"><span>動画一覧</span> <i class="fa fa-caret-down pull-right"></i></a>
          <ul class="treeview-menu">
            <!--for free_engineer_users-->
            <% if current_user.free_engineer_user %>
              <% free_movie_categories.each do |category| %>
                <li><%= link_to category.name, movie_category_path(category), class: "#{'disabled' unless before_category_comp?(category)}" %></li>
              <% end %>
            <% end %>
            <!--for venture users-->
            <% if current_user.venture_user %>
              <% venture_movie_categories.each do |category| %>
                <li><%= link_to category.name, movie_category_path(category), class: "#{'disabled' unless before_category_comp?(category)}" %></li>
              <% end %>
            <% end %>
            <!--for staff_users-->
            <% if current_user.staff_user %>
              <% staff_movie_categories.each do |category| %>
                <li><%= link_to category.name, movie_category_path(category), class: "#{'disabled' unless before_category_comp?(category)}" %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
  		
        <li><%= link_to 'プログラミングの基礎編', basic_programming_path, class: "#{'disabled' unless movie_comp?}" %></li>
        <li><%= link_to '誰でもわかる勤怠システム', attendance_system_path, class: "#{'disabled' unless progatetask_tutolialday_comp?}" %></li>
        <!--<li><#%= link_to 'ポートフォリオの作り方', portfolio_mv_path, class: "#{'disabled' unless railstutorial_comp? }" %></li>-->
        <li><%= link_to 'よくある質問', faq_index_path, class: "#{'disabled' if current_user.try(:guest) }" %></li>
        <li><%= link_to 'Qiita投稿まとめ', qiita_posts_path, class: "#{'disabled' if current_user.try(:guest) }" %></li>
        <li><%= link_to '面談内容共有', interview_posts_path, class: "#{'disabled' if current_user.try(:guest) }" %></li>
        <li><%= link_to 'IT用語解説', terms_path, class: "#{'disabled' if current_user.try(:guest) }" %></li>
        <li><%= link_to 'PDCA報告', pdca_posts_path, class: "#{'disabled' if current_user.try(:guest) }" %></li>
        <li><%= link_to '不具合報告', defect_forms_path  %></li>
        <li><%= link_to 'Blog一覧', blogs_path %></li>
      <% end %><!--unless current_user.guest-->
      
      <li><%= link_to 'スキルシート一覧', skillsheets_path %></li>
    </ul><!-- /.sidebar-menu -->

  </section>
</aside>

Celebrity/app/views/layouts/_navbar.html.erb
<header class="main-header">
  <!--logo-->
  <!--    <= link_to root_path, class: "link-to-top" do %>-->
  <!--      <= image_tag "logo_header.png", id: "logo-header" %>-->
  <!--    < end %>-->
  <%= link_to 'Celebrity Engineering', root_path, class: "logo" %>
  <nav class="navbar navbar-static-top" role="navigation">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only">Toggle navigation</span>
    </a>
    <!-- Navbar Right Menu -->
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <!-- Notifications Menu -->
        <!--<li class="dropdown notifications-menu">-->
        <!--  <a href="#" class="dropdown-toggle" data-toggle="dropdown">-->
        <!--    <i class="fa fa-bell-o"></i>-->
        <!--    <span class="label label-warning">10</span>-->
        <!--  </a>-->
        <!--</li>-->
        
        <!-- User Account Menu -->
        <li class="dropdown user user-menu">
          <!-- Menu Toggle Button -->
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <!-- The user image in the navbar-->
            <!--<img src="https://almsaeedstudio.com/themes/AdminLTE/dist/img/user2-160x160.jpg" class="user-image" alt="User Image">-->
            <% if current_user.picture_file %>
              <%= image_tag(get_image_user_path(current_user), class: "user-image") %>
            <% else %>
              <%= image_tag('default.png', class: "user-image") %>
            <% end %>
            <!-- hidden-xs hides the username on small devices so only the image appears. -->
            <span class="hidden-xs"><%= current_user.name %></span>
          </a>
          <ul class="dropdown-menu">
            <!-- The user image in the menu -->
            <li class="user-header">
              <!--<img src="https://almsaeedstudio.com/themes/AdminLTE/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">-->
              <% if current_user.picture_file %>
                <%= image_tag(get_image_user_path(current_user), class: "img-circle") %>
              <% else %>
                <%= image_tag('default.png', class: "img-circle") %>
              <% end %>
              <p><%= current_user.name %></p>
            </li>
            
            <% unless current_user.try(:guest) %>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-10 col-xs-offset-1 text-center">
                    <%= link_to 'SALON MEMBER', users_path %>
                  </div>
                </div>
              </li>
            
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-10 col-xs-offset-1 text-center">
                    <%= link_to 'MY PAGE', current_user %>
                  </div>
                </div>
              </li>
            
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-6 col-xs-offset-3 text-center">
                    <%= link_to logout_path, method: :delete do %>
                      <i class="fa fa-sign-out"></i>Sign Out
                    <% end %>
                  </div>
                </div>
              </li>
            <% end %>
          </ul>
        </li>
        <!-- Control Sidebar Toggle Button -->
        <!--<li>-->
        <!--  <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a>-->
        <!--</li>-->
      </ul>
    </div>
  </nav>
</header><!-- end header -->

<!--<div class="header">-->
<!--  <div class="content-wrap">-->
    
    <!--▼ロゴ-->
<!--    <= link_to root_path, class: "link-to-top" do %>-->
<!--      <= image_tag "logo_header.png", id: "logo-header" %>-->
<!--    < end %>-->
    
<!--    <div class="nav-button" >-->
<!--      <span></span>-->
<!--      <span></span>-->
<!--      <span></span>-->
<!--    </div>-->
    
<!--    <nav class="nav-wrap">-->
<!--      <ul class="nav-ul">-->
<!--        < unless current_user.try(:guest) %>-->
<!--        <li><= link_to 'TOP', root_path %></li>-->
<!--        < end %>-->
        
        <!--adminのみ表示-->
<!--        < if current_user.try(:admin) %>-->
<!--          <li><= link_to 'MOVIES EDIT', movies_path %></li>-->
<!--          <li><= link_to 'INFO EDIT', information_path %></li>-->
<!--          <li><= link_to 'BLOG EDIT', new_blog_path %></li>-->
<!--          <li><= link_to 'SIGN UP', signup_path %></li>-->
<!--        < end %>-->
        
        <!--全ユーザー-->
<!--        < unless current_user.try(:guest) %>-->
<!--        <li><= link_to 'SALON MEMBERS', users_path %></li>-->
<!--        <li><= link_to 'MY PAGE', current_user %></li>-->
<!--        < end %>-->
<!--        <li><= link_to 'LOG OUT', logout_path, method: :delete %></li>-->
<!--      </ul>-->
<!--    </nav>-->
    
<!--  </div>-->
<!--</div>-->

<!--<script>-->
<!--  (function() {-->
<!--    $('.nav-button').on('click',function(){-->
<!--      if( $(this).hasClass('active') ){-->
<!--        $(this).removeClass('active');-->
<!--        $('.nav-wrap').addClass('close').removeClass('open');-->
<!--      }else {-->
<!--        $(this).addClass('active');-->
<!--        $('.nav-wrap').addClass('open').removeClass('close'); -->
<!--      }-->
<!--    });-->
<!--  }());-->
<!--</script>-->

Celebrity/app/views/layouts/_progress.html.erb
<div>
	<p class="text-center"><a href="https://prog-8.com/mypage">プロゲートはこちら</a></p>
	<%= bootstrap_form_tag url:'/progate', html: {class: 'form-group'}, :remote => true  do |f| %>
	  <%= f.submit "初級未完了", class: "btn btn-primary btn-lg progress-btn", disabled: false %>
	  <%= f.submit "中級未完了", class: "btn btn-primary btn-lg progress-btn", disabled: true %>
	<% end %>
</div>

<script>


</script>

Celebrity/app/views/layouts/form1.html.erb
<p class="text-center">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/B-IQt9NXb5A" frameborder="0" allowfullscreen></iframe>
    <button type="button" id="show-feedback-form" class="btn btn-lg btn-primary" data-toggle="modal">感想を送る！</button>
    <p id="alert" class="text-center">感想を再送する場合はページを再読み込みしてください</p>
</p>

<%= bootstrap_form_tag url:'/progate', html: {class: 'form-group'}, :remote => true  do |f| %>
  <%= f.text_area :impression ,:id => "Tobj1", :size=>"7x7", :maxlength => "500",
      :placeholder => "100-500文字で入力してください", required: true, :onchange => "Limit(event)", :onkeyup => "Limit(event)" %>
      <br><span id="msg1">文字数カウント</span><br><div style="color: red;" class="has-error"></div>
  <%= f.submit "感想を送る", id:"feedback-btn" , class: "btn btn-primary btn-lg submit-btn", disabled: true %>
  
<% end %>


<!--検証用に複数ボタンを配置する-->
<%= bootstrap_form_tag url:'/progate', :remote => true  do |f| %>
 <%= f.submit '初級未完了', name: 'beginner' ,class: 'btn btn-danger' %>
<% end %>

<%= bootstrap_form_tag url:'/progate', :remote => true  do |f| %>
 <%= f.submit '中級未完了', name: 'intermediate' ,class: 'btn btn-danger' ,disabled: true %>
<% end %>

<%= bootstrap_form_tag url:'/progate', :remote => true  do |f| %>
 <%= f.submit '上級未完了', name: 'expert' ,class: 'btn btn-danger' ,disabled: true %>
<% end %>


<!--検証用 progate.js で入力内容を受け取り、下記に出力している-->
<input type="textarea" rows="7" cols="7" id="result">
    
    
<% if @msg %>
    <%= msg %>
<% end %>


<script>
$(function(){
    $('.form-group').hide();
    $('#alert').hide();
});
$(function() {
    $('#show-feedback-form').click(function(){
        $('.form-group').show();
        $(this).fadeOut();
    });
});
</script>

<script language="JavaScript">
var str1 = document.js.authenticity_token.value;
var max=500; //制限文字数
var min=100;
function Limit(event){
Tarea= document.getElementById("Tobj1");
  Mcnt= document.getElementById("msg1");
  mojiVal= Tarea.value; //テキストエリアの文字数
  val= mojiVal.replace(/\n|\r\n/g,"");//改行を除く
  val= val.length; //改行を含めない文字数
    Etype=event.type; //イベントのタイプを取得

if(Etype== "keyup"){//イベントのタイプが"Keyup"なら
  Mcnt.innerHTML= //文字数のカウントを表示
"<span style='font-weight: bold;color:blue ;'>"+val+"</span>文字";
  }
}

</script>
<script>

$(function(){
    var     $text = $("textarea"),
            $button = $('.submit-btn'),
            disabled_class = 'disabled';
 
    if($text.val().length == 0) {
        $button.prop('disabled',true).addClass('disabled');
    }
 
    $text.bind('keydown keyup keypress change',function(){
        var thisValueLength = $(this).val().length;
        if(thisValueLength >= 100){
            $button.prop('disabled',false).removeClass(disabled_class);
            jQuery( '.has-error' ).hide();
        }else{
            $button.prop('disabled',true).addClass(disabled_class);
            jQuery( '.has-error' ) . text( '100文字以上入力してください' );
            jQuery( '.has-error' ).show();
        }
    });
});
</script>

<script>
$(function() {
     $('#feedback-btn').click(function(){
         $(this).val('送信完了');
         $(this).prop('disabled', true);
         $('#Tobj1').fadeOut();
         $('#msg1').fadeOut();
         $('.control-label').fadeOut();
         $('#alert').fadeIn();
     });

     
     $('input[name="beginner"]').click(function(){
         $(this).val('初級完了')
         $('input[name="intermediate"]').prop('disabled', false);
     })
     
     $('input[name="intermediate"]').click(function(){
         $(this).val('中級完了')
         $('input[name="expert"]').prop('disabled', false);
     })
     
     $('input[name="expert"]').click(function(){
         $(this).val('上級完了')
     })
});
</script>