config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/new'
  get 'password_resets/edit'

  get '/signup', to:'users#new'
  post '/signup', to:'users#create'

  get '/login', to:'sessions#new'
  post '/login', to:'sessions#create'
  
  # 画像データの取得
  get '/show_image', to: 'application#show_image'
  
  delete '/logout', to:'sessions#destroy'
  get 'skillsheets/index'
  get 'skillsheets/download'
  get 'skillsheets/update_skillsheet'
  get 'skillsheets/search'#追記
  resources :users do
      member do
        get 'get_image'
        get 'get_skillsheet'
    end
  end
  
  resources :pdca_posts
  resources :defect_forms
  resources :qiita_posts
  resources :interview_posts
  resources :account_activations, only: [:edit]
  resources :feedbacks, only: [:create, :update, :destroy]
  resources :comments, only: [:create, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :blogs
  
  resources :movies do
    get 'sort', on: :collection
  end
  resources :movie_categories do
    get 'sort', on: :collection
  end
  resources :skillsheets
  get '/get_skillsheet', to: 'skillsheets#get_skillsheet'
  get '/index', to: 'skillsheets#index'
  patch '/update_business_status', to: 'skillsheets#update_business_status'
  resources :terms do
    collection do
      get 'ajax_search'
    end
  end
  resources :users do
      member do
        get 'get_image'
        get 'get_skillsheet'
    end
  end
  
  post '/tag_new', to: 'users#tag_new'
  delete '/tag_delete', to: 'users#tag_delete'
  
  # patch '/post_course', to:'users#update_course'
  patch '/post_pic', to:'users#update_picture'
  patch '/tag_edit', to:'users#tag_edit' #追加
  patch '/tag_show', to:'users#tag_show' #追加 sugi
  delete '/delete_tag', to: 'users#tag_delete' #temp post⇨deleteに変更しshow.htmlと統一
  patch '/post_skillsheet', to: 'skillsheets#update_skillsheet'
  patch '/register_status', to: 'users#register_status'
  root 'top#index'
  
  get '/information', to: 'information#show'
  post '/information', to: 'information#create', as: 'create_information'
  patch '/information', to: 'information#update'
  delete '/information', to: 'information#destroy'

  get '/progate', to: 'static_pages#progate'
  post '/progate', to: 'static_pages#progate'
  get '/railstutorial', to: 'static_pages#railstutorial'
  get '/portfolio', to: 'portfolio_comments#portfolio'
  post '/comments/create', to: 'portfolio_comments#create'
  post '/comments/:id/destroy', to: 'portfolio_comments#destroy'
  get '/qa', to: 'static_pages#qa'
  get '/portfolio_mv', to: 'static_pages#portfolio_mv'
  post '/defect_forms/notify_to_slack', to: 'defect_forms#notify_to_slack'
  patch '/html_css_status', to: 'html_css_statuses#update'
  patch '/html_css_status_schedule', to: 'html_css_statuses#update_schedule', as: 'html_css_schedule'
  patch '/html_css_status_completion', to: 'html_css_statuses#update_completion', as: 'html_css_completion'
  patch '/javascript_status', to: 'javascript_statuses#update'
  patch '/javascript_status_schedule', to: 'javascript_statuses#update_schedule', as: 'javascript_schedule'
  patch '/javascript_status_completion', to: 'javascript_statuses#update_completion', as: 'javascript_completion'
  patch '/ruby_status', to: 'ruby_statuses#update'
  patch '/ruby_status_schedule', to: 'ruby_statuses#update_schedule', as: 'ruby_schedule'
  patch '/ruby_status_completion', to: 'ruby_statuses#update_completion', as: 'ruby_completion'
  patch '/rubyonrails_status', to: 'rubyonrails_statuses#update'
  patch '/rubyonrails_status_schedule', to: 'rubyonrails_statuses#update_schedule', as: 'rubyonrails_schedule'
  patch '/rubyonrails_status_completion', to: 'rubyonrails_statuses#update_completion', as: 'rubyonrails_completion'
  patch '/railstutorial_status', to: 'railstutorial_statuses#update'
  patch '/railstutorial_status_schedule', to: 'railstutorial_statuses#update_schedule', as: 'railstutorial_schedule'
  patch '/user_movie_status', to: 'user_movie_statuses#update'
  patch '/user_movie_status_schedule', to: 'user_movie_statuses#update_schedule', as: 'user_movie_schedule'
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  include SessionsHelper
  acts_as_paranoid
  has_many :movies, dependent: :destroy
  validates :name, presence: true, length: { maximum: 12 }
end

app/controllers/movie_categories_controller.rb
class MovieCategoriesController < ApplicationController
  include MovieCategoriesHelper
  
  before_action :logged_in_user
  before_action :admin_user, only: [:index, :new, :create, :edit, :update, :destroy, :sort]
  before_action :comp_movies, only: :show
  before_action :viewing_restriction, only: :show
  before_action :check_guest_user
  
  def index
    @categories = MovieCategory.all.order('sort_order')
  end

  def show
    @movies         = Movie.where(movie_category_id: params[:id]).order('sort_order')
    @category       = MovieCategory.find_by(id: params[:id])
    @categories_all = MovieCategory.all.order('sort_order')
    @next_category  = MovieCategory.find_by(sort_order: @category.sort_order + 1)
    
    @feedback = current_user.feedbacks.build
  end

  def new
    @movie_category = MovieCategory.new
  end
  
  def create
    params[:movie_category][:sort_order] = MovieCategory.all.pluck(:sort_order).max.to_i + 1
    @movie_category = MovieCategory.new(movie_category_params)
    if @movie_category.save
      flash[:success] = '動画カテゴリを登録しました'
      redirect_to movies_path
    else
      flash.now[:danger] = '登録に失敗しました。もう一度お試しください。'
      render 'new'
    end
  end
  
  def edit
    @movie_category = MovieCategory.find_by(id: params[:id])
    @movies = Movie.where(movie_category_id: params[:id]).order('sort_order')
  end
  
  def update
    @movie_category = MovieCategory.find_by(id: params[:id])
    if @movie_category.update_attributes(movie_category_params)
      flash[:success] = '動画カテゴリ情報を更新しました' 
      redirect_to movies_path
    else
      render 'edit'
    end
  end

  def destroy
    @movie_category = MovieCategory.find_by(id: params[:id])
    delete_order = @movie_category.sort_order
    @movie_category.update_attributes(sort_order: 0)
    if @movie_category.destroy  # 論理削除
      MovieCategory.where(['sort_order > ?', delete_order]).try(:each) do |mc|
        mc.update_attributes(sort_order: mc.sort_order - 1)
      end
      flash[:success] = '動画カテゴリを削除しました'
      redirect_to movies_path
    end
  end
  
  def sort
    @categories = MovieCategory.all
    sort_num = params[:sort_up].present? ? params[:sort_up].to_i : params[:sort_down].to_i

    if params[:sort_up].present?
      @sort_up_category   = @categories.find_by(sort_order: sort_num)
      @sort_down_category = @categories.find_by(sort_order: sort_num - 1)
  
      @sort_up_category.update_attributes(sort_order: sort_num - 1)
      @sort_down_category.update_attributes(sort_order: sort_num)

    else
      @sort_up_category   = @categories.find_by(sort_order: sort_num + 1)
      @sort_down_category = @categories.find_by(sort_order: sort_num)
  
      @sort_up_category.update_attributes(sort_order: sort_num)
      @sort_down_category.update_attributes(sort_order: sort_num + 1)
    end

    @categories = MovieCategory.all.order('sort_order')
 
    respond_to do |format|
      format.js
    end
  end

  private
  
    def movie_category_params
      params.require(:movie_category).permit(:name, :sort_order, :must_view, :subject)
    end
    
    def comp_movies
      @category  = MovieCategory.find_by(id: params[:id])
      if before_category_comp?(@category)
      else
        flash[:danger] = "先に前の動画を視聴して下さい"
        redirect_to root_url
      end
    end
    
    def viewing_restriction
      @category = MovieCategory.find_by(id: params[:id])

        if @category.subject == "free"
          unless current_user.free_engineer_user
            flash[:danger] = "動画の視聴権限がありません。"
            redirect_to root_url
          end
        elsif @category.subject == "venture"
          unless current_user.venture_user
            flash[:danger] = "動画の視聴権限がありません。"
            redirect_to root_url
          end
        elsif @category.subject == "staff"
          unless current_user.staff_user
            flash[:danger] = "動画の視聴権限がありません。"
            redirect_to root_url
          end
        end
    end
end

app/helpers/movie_categories_helper.rb
module MovieCategoriesHelper
  
  # 全動画カテゴリの呼び出し
  def all_movie_categories
    MovieCategory.order('sort_order')
  end
  
  def free_movie_categories
    MovieCategory.where(subject: 'free').order('sort_order')
  end
  
  def venture_movie_categories
    MovieCategory.where(subject: 'venture').order('sort_order')
  end
  
  def staff_movie_categories
    MovieCategory.where(subject: 'staff').order('sort_order')
  end
  
  # 動画カテゴリ毎の閲覧状況を判定
  def before_category_comp?(category)
    if category.subject == 'free'
      if category.sort_order == 1
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order - 1).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order - 1).must_view
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order).must_view
        return true
      end
      target_movie_ids = MovieCategory.find_by(sort_order: category.sort_order - 1).movies.pluck(:id)
      sent_movie_ids   = current_user.feedbacks.pluck(:movie_id)
      target_movie_ids.each do |id|
        return false unless sent_movie_ids.include?(id)
      end
      return true
    elsif category.subject == 'venture'
      if category.sort_order == MovieCategory.where(must_view: true).where(subject: 'venture').minimum(:sort_order)
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order - 1).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order - 1).must_view
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order).must_view
        return true
      end
      target_movie_ids = MovieCategory.find_by(sort_order: category.sort_order - 1).movies.pluck(:id)
      sent_movie_ids   = current_user.feedbacks.pluck(:movie_id)
      target_movie_ids.each do |id|
        return false unless sent_movie_ids.include?(id)
      end
      return true
    elsif category.subject == 'staff'
      if category.sort_order == MovieCategory.where(must_view: true).where(subject: 'staff').minimum(:sort_order)
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order - 1).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order - 1).must_view
        return true
      end
      if !MovieCategory.find_by(sort_order: category.sort_order).blank? &&
        !MovieCategory.find_by(sort_order: category.sort_order).must_view
        return true
      end
      target_movie_ids = MovieCategory.find_by(sort_order: category.sort_order - 1).movies.pluck(:id)
      sent_movie_ids   = current_user.feedbacks.pluck(:movie_id)
      target_movie_ids.each do |id|
        return false unless sent_movie_ids.include?(id)
      end
      return true
    end
  end
  
  # 感想の提出状況を判定 ※未使用のためコメントアウト（2018/03/08 春海）
  # def send_feedbacks_comp?
  #   sent_movie_ids = current_user.feedbacks.pluck(:movie_id)
  #   last_category = MovieCategory.find_by(sort_order:  MovieCategory.count)
  #   return false if last_category.nil?
  #   if last_category.try(:movies).present?
  #     last_movie_id = last_category.movies.order('sort_order').last.id
  #   else
  #     last_movie_id = MovieCategory.find_by(sort_order: MovieCategory.count - 1).movies.order('sort_order').last.id
  #   end

  #   return sent_movie_ids.include?(last_movie_id) ? true : false
  # end
end

app/views/movie_categories/_feedback_form.html.erb
<div id="form-group<%= sort_order %>" class="movie-feedback-form--wrapper">
  <%= form_for(feedback, remote: true, html:{:id => 'feedback-form'}) do |f| %>
    <!--文字数カウント・エラーメッセージ-->
    <p id="msg<%= sort_order %>" class="movie-feedback-form--count">文字数カウント</p>
    <p id="has-error<%= sort_order %>" class="movie-feedback-form--error-message"></p>
    <!--感想入力フォーム-->
    <div class="">




      <!--提出済みの感想を初期値にセットする-->
      <% if current_user.feedbacks.find_by(movie_id: movie_id) %>
       <% @feedback.feedback = current_user.feedbacks.find_by(movie_id: movie_id).feedback %>
      <% else %>
        <% @feedback.feedback = '' %>
      <% end %>
      <%= f.text_area :feedback, :id => "textarea#{sort_order}",
        :class => "movie-feedback-form--textarea  validate[required,minSize[100],maxSize[500]] text-input",
        :size => "7x7", :maxlength => "500", :placeholder => "100-500文字で入力してください", required: true, 
        :onchange => "Limit#{sort_order}(event)", :onkeyup => "Limit#{sort_order}(event)" %>
      <%= f.hidden_field :movie_id, :value => movie_id %>
    </div>
    <!--送信ボタン-->
    <div id="feedback-btn<%= sort_order %>" class="center">
      <%= image_submit_tag("button_feedback1.png", id: "submit-btn#{sort_order}",class: "img-feed-btn", disabled: true) %>        
    </div>
  <% end %>
</div>


<script>
$(function(){
    $('#form-group<%= sort_order %>').hide();

    $('#show-form<%= sort_order %>').click(function(){
        $('#form-group<%= sort_order %>').show(500);
        $(this).fadeOut(500);
    });
});

function Limit<%= sort_order %>(event){
  var Tarea<%= sort_order %>= document.getElementById("textarea<%= sort_order %>");
  var Mcnt<%= sort_order %>= document.getElementById("msg<%= sort_order %>");
  var mojiVal<%= sort_order %> = Tarea<%= sort_order %>.value; //テキストエリアの文字数
  var val<%= sort_order %> = mojiVal<%= sort_order %>.replace(/\n|\r\n/g,"").length;
  var Etype<%= sort_order %> = event.type; //イベントのタイプを取得
if(Etype<%= sort_order %> == "keyup"){//イベントのタイプが"Keyup"なら
  Mcnt<%= sort_order %>.innerHTML = //文字数のカウントを表示
    "<span style='font-weight: bold;color:blue ;'>"+val<%= sort_order %>+"</span>文字";
  }
}

$(function(){
    var $text<%= sort_order %> = $("#textarea<%= sort_order %>"),
        $button<%= sort_order %> = $("#submit-btn<%= sort_order %>"),
        disabled_class = 'disabled';
 
    if($text<%= sort_order %>.val().length == 0) {
        $button<%= sort_order %>.prop('disabled',true).addClass('disabled');
    }
 
    $text<%= sort_order %>.bind('keydown keyup keypress change',function(){
        var thisValueLength = $(this).val().length;
        if(thisValueLength >= 100){
            $button<%= sort_order %>.prop('disabled',false).removeClass(disabled_class);
            $('#has-error<%= sort_order %>').hide();
        }else{
            $button<%= sort_order %>.prop('disabled',true).addClass(disabled_class);
            $('#has-error<%= sort_order %>').text( '100文字以上入力してください' );
            $('#has-error<%= sort_order %>').show();
        }
    });
});

  $(document).ready(function(){
    $("#feed-form").validationEngine();
  });

</script>

app/views/movie_categories/_movie.html.erb
<h4 class="movie-title"><%= movie.title %></h4>
<div class="movie">
  <div id="movie-layer" class="movie-layer">セレブエンジニアリング</div>
  <% param = '?modestbranding=1' %>
  <div class="iframe-responsive">
  <iframe width="480" height="340" src="<%= movie.path + param %>" frameborder="0" allowfullscreen  oncontextmenu='return false'></iframe>
</div>
</div>



<% if @category.must_view %>
  <div class="mv-btn">
    <% if current_user.feedbacks.find_by(movie_id: movie.id) %>
      <%= image_submit_tag("button_feedback2.png", id: "show-form#{movie.sort_order}", class: "img-feed-btn") %>
    <% else %>
      <%= image_submit_tag("button_feedback1.png", id: "show-form#{movie.sort_order}", class: "img-feed-btn") %>
    <% end %>
  </div>
<% end %>

app/views/movie_categories/_movie_category_form.html.erb
<div class="category-form">
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <%= form_for(@movie_category, html:{:id => 'movie-category-form'}) do |f| %>

        <div class="form-group">
          <%= f.label :name, 'カテゴリ名', class: 'txt3' %>
          <%= f.text_field :name, class: 'form-control validate[required,maxSize[12]] text-input', :onkeyup => "NameLength(value);" %>
          <p id="name-input-length">0文字</p>
        </div>

        <div class="form-inline">
          <label class="checkbox-inline">
            <%= f.check_box :must_view, {}, 'true', 'false' %>
            感想送信を必須にする
          </label>
        </div>
        
        <div class="form-group">
          <label class="txt3">コース選択</label>
          <div class="form-inline">
            <label class="checkbox-inline">
              <%= f.radio_button :subject, "free" %>
              フリーエンジニア養成コース
            </label>
          </div>
          <div class="form-inline">
            <label class="checkbox-inline">
              <%= f.radio_button :subject, "venture"%>
              ITベンチャー起業コース
            </label>
          </div>
         <div class="form-inline">
            <label class="checkbox-inline">
              <%= f.radio_button :subject, "staff"%>
              スタッフ権限付与
            </label>
          </div></div>
  
        <%= f.submit "登録", class: "btn-log btn btn-default active" %>
      <% end %>
    </div>
  </div>
</div>

<script>
  $(document).ready(function(){
    $("#movie-category-form").validationEngine();
  });
  
  function NameLength( str ) {
    document.getElementById("name-input-length").innerHTML = str.length + "文字";
  }
  

</script>

app/views/movie_categories/_sort_table.html.erb
<table class="table table-bordered table-striped table-index">
  <thead>
    <tr>
      <th class="table-header" width="80%">カテゴリ</th>
      <th class="table-header">Up</th>
      <th class="table-header">Down</th>
    </tr>
  </thead>
  <% categories.each_with_index do |category, i| %>
    <tbody>
      <tr>
        <td class="left">【<%= category.sort_order %>】<%= category.name %></td>
        <td>
          <% if i >= 1 %>
            <%= link_to sort_movie_categories_path(sort_up: category.sort_order), remote: true do %>
              <span class="arrow-up"></span>
            <% end %>
          <% end %>
        </td>
        <td>
          <% if i < categories.count - 1 %>
            <%= link_to sort_movie_categories_path(sort_down: category.sort_order), remote: true do %>
              <span class="arrow-down"></span>
            <% end %>
          <% end %>
        </td>
      </tr>
    </tbody>    
  <% end %>
</table>

app/views/movie_categories/new.html.erb
<h2 class="page-title-jp">
  <span>動画カテゴリ登録</span>
</h2>

<%= render :partial => 'movie_category_form' %>

<div class="center mt_20">
  <%= link_to '<< 動画一覧へ戻る', movies_path %>
</div>

app/views/movie_categories/show.html.erb
<div class="moviecategories-show--wrapper">
  
  <h2 class="page-title-jp">
    <span><%= @category.name %></span>
  </h2>
  
  <% hide = 'hide-movie' %>
  <% @movies.each do |movie| %>
    <div id="m<%= movie.sort_order %>" class="<%= hide if !current_user.before_fb_comp?(movie.sort_order, @category.id) && @category.must_view %>">
      <%= render 'movie', movie: movie %>
      <% if @category.must_view %>
        <%= render 'feedback_form', feedback: @feedback, sort_order: movie.sort_order, movie_id: movie.id %>
      <% end %>
    </div>
  <% end %>
  
  
  <% if (current_user.free_engineer_user && current_user.venture_user && current_user.staff_user) %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif (current_user.free_engineer_user && current_user.venture_user) %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: ['free', 'venture']).count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif (current_user.free_engineer_user && current_user.staff_user) %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: ['free', 'staff']).count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif (current_user.venture_user && current_user.staff_user) %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: ['staff', 'venture']).count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif current_user.free_engineer_user %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: 'free').count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif current_user.venture_user %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: 'venture').count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% elsif current_user.staff_user %>
    <% if @category.sort_order == MovieCategory.where(must_view: true).where(subject: 'staff').count %>
      <div id="mypage_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <div class="txt1">
          おめでとうございます！<br>
          課題となる動画視聴はこれで完了です。<br>
          次はProgate完了予定日の登録に進みましょう！<br>
        </div>
        <p class="text-center">  
          <%= link_to "完了予定日を登録", current_user, class: "txt1 btn btn-lg btn-default active" %>
        </p>
      </div>
    <% elsif @category.sort_order != MovieCategory.count %>
      <div id="next_category_link" class="<%= hide if !current_user.before_fb_comp?(@category.movies.count + 1, @category.id) && @category.must_view %>">
        <p class="text-center">
          <% if !@next_category.blank? %>
            <%= link_to "NEXT：#{@next_category.name}", movie_category_path(@next_category), class: "txt1 btn btn-lg btn-default active" %>
          <% end %>
        </p>
      </div>
    <% end %>
  <% end %>
</div>
    
<script>
  $('.hide-movie').hide();
</script>